name: containers-focus
version: 0.1.0.0

ghc-options: -Wall

dependencies:
  - base

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - containers-focus
      - hspec
